### PR TITLE
Development

### PR DESCRIPTION
**Pull request by PromoFaux**
asdsad

### CODE REVIEW

**Comment by brantje** [comment]
:shipit:

**Comment by dschaper** [comment]
Reject

**Comment by dschaper** [comment]
Rejected

**Comment by PromoFaux** [comment]
` reject_regex: '^(Rejected|:-1:|Borg)'` ;)

**Comment by PromoFaux** [comment]
image

**Comment by dschaper** [comment]
Yeah, too much shtuff in my head... lol...

**Comment by PromoFaux** [comment]
:+1:

**Comment by dschaper** [comment]
So one vote can still be overridden, 2 to block outright I think?

**Comment by PromoFaux** [comment]
I cannot vote manually at all

**Comment by PromoFaux** [comment]
As the author, that is.

**Comment by dschaper** [comment]
Does Jacobs vote count for both branches? And is that a bad thing?

**Comment by PromoFaux** [comment]
Jacob get's two different votes

`Approved/+1/engage`

and a `Make it so` for push to master

**Pull request closed without merging**
